### ISSUE TITLE
`quote: true` for column in `.yml` properties causes tests not to render in TESTS column in the Column table

### ISSUE THREAD

**Issue by barberscott** [dbt-labs/dbt-docs#201]
Given model `docs_test.sql` with:
```
select 'foo' as "My Space", 'bar' as "NoSpace"
```

and `docs_test.yml` with:
```
version: 2

models:
  - name: docs_test
    columns:  
      - name: My Space
        quote: true
        tests:
        - not_null
      - name: NoSpace
        quote: true
        tests:
        - not_null
```

a `dbt docs generate` runs but when I got to view docs I don't see docs for either referenced under the TESTS column in the Columns table in the browser.

This code in the underlying javascript `<!-- ngIf: has_test(column, 'N') -->` doesn't seem to be able to find the column when quote: true is applied.   [That source is here.](https://github.com/dbt-labs/dbt-docs/blob/master/src/app/components/column_details/column_details.js#L17-L20).

![Screen Shot 2021-07-08 at 4 56 24 PM](https://user-images.githubusercontent.com/74067474/124998433-069e4180-e012-11eb-8598-5016f7eb67da.png)

Things I tried to work around:
- Removing quote works for docs, but then breaks the test since I need to preserve lettercase and/or the space here.
- Adding quotes to name: like `"'My Space'"` allows the test to work, but results in a double entry in docs.

![Screen Shot 2021-07-08 at 5 02 14 PM](https://user-images.githubusercontent.com/74067474/124998411-fede9d00-e011-11eb-9066-cf0082ccd124.png)
