### ISSUE TITLE
Meta configs in model details are not rendered in docs site

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-docs#230]
### Describe the bug
Models [meta config](https://docs.getdbt.com/reference/resource-configs/meta) are not being rendered in the docs site. Columns meta config however are rendered just fine.

### Steps To Reproduce
With a very basic project and the following `schema.yml` file:

```yml
version: 2

models:
  - name: my_model
    description: "Test description"
    config:
      meta:
        contains_pii: "true"
    columns:
      - name: user_name
        meta:
          contains_pii: "true"
  - name: my_model_2
    config:
      meta:
        my_meta: "test"
    columns:
      - name: user_name
        meta:
          my_meta: "test"
```

Generate docs (`dbt docs generate`) and then inspect them.

### Expected behavior
Config meta key-values should render under model details just like column details.

### Screenshots and log output
![Screen Shot 2022-01-17 at 11 49 21 AM](https://user-images.githubusercontent.com/8496748/149681367-a253ab28-01f5-468a-8ffc-5e655b39c2d1.png)

Gif:
![2022-01-17 11 00 01](https://user-images.githubusercontent.com/8496748/149681109-5defea93-7c59-44c7-ab5f-1c01b1213b84.gif)

**The output of `dbt --version`:**
```
1.0.1
```
Tested in both core and cloud but same behaviour.

### Additional context
This behaviour is also reproduced when using the meta config within the model file itself:

```sql
-- my_model.sql

{{ config(meta = {'contains_pii': 'true'}) }}

select 1 as user_name
```

Note that this doesn't affect dbt execution in terms of selection models to run via the meta config (e.g. `dbt run -s config.meta.contains_pii:true`) but more of a UI rendering issue with the docs site.

Best guess currently is due to this: https://github.com/dbt-labs/dbt-docs/blob/main/src/app/components/table_details/table_details.js#L23 (though to be honest, not really that familiar with the docs site / angular).
