### ISSUE TITLE
Documentation stuck in loading page in case of unsupported test references in `schema.yml`

### ISSUE THREAD

**Issue by zhegedus13** [dbt-labs/dbt-docs#241]
### Describe the bug
dbt Documentation will stuck in loading page in case model tests are written in bundled format in `schema.yml` 

### Steps To Reproduce
In `schema.yml` referencing the not null tests the following way will cause the issue to surface: 
```
models:
  - name: my_sql_model
    description: something my sql model does
    tests:
      - not_null:
          column_name:
            - date
            - customer_id
            - value
            - amount
            - etc...
```

### Expected behavior
After `dbt docs generate` and `dbt docs serve` and opening the documentation in the browser, it will be stuck in loading page, never rendering the catalog (neither will this give a notification that `schema.yml` tests are the cause of the issue) .  

### Additional context
A workaround exists for the issue in case not null tests are referenced in a different (although more redundant) manner: 
```
models:
  - name: my_sql_model
    description: something my sql model does
      - name: date
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: value
        tests:
          - not_null
      - name: amount
        tests:
          - not_null
      - etc... 
```

**Comment by emmyoop** [comment]
@zhegedus13 thanks for writing this up and providing a clear example.  The example you provide is actually not a valid way to define tests.  `columns_name` cannot take a list of columns.  You could define it as:

```
models:
  - name: my_sql_model
    description: something my sql model does
    tests:
      - not_null:
          column_name: 'date'
```

I'm guessing that your docs are not loading because they have not generated.  When I try to generate docs with a list of columns as you describe above, I get a Parsing Error and they do not generate.

I'm going to close this issue since it is not a bug in the docs.  Feel free to comment if you disagree.
