### ISSUE TITLE
[CT-2332] [CT-2330] [Bug] Documentation for csv files is not displaying the table name in the Example SQL section

### ISSUE THREAD

**Issue by andrea-montes-yello** [dbt-labs/dbt-docs#407]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

after running dbt docs serve, the documentation tied to a seed csv file is not showing the table name in the example SQL section. Instead of the table name, it is displaying undefined.

### Expected Behavior

The table name should be displayed in the section Example SQL

### Steps To Reproduce

1. Create documentation for a seed file
2. dbt docs generate
3. dbt docs serve
4. Navigate to the seed documentation
5. Check what's in the section Example SQL

### Environment

```markdown
- OS: Mac OS monterrey 12.5.1
- Python: Python 3.8.9
- dbt: 1.3.1
```

### Which database adapter are you using with dbt?

postgres

**Comment by dbeatty10** [comment]
Good find @andrea-montes-yello !

I think the fix could be as simple as updating this:
https://github.com/dbt-labs/dbt-docs/blob/ac6670cad4eb60356b50eec23496aa56c6774635/src/app/services/code_service.js#L59

To this instead:
```js
        const rel = database + model.schema + "." + model.name;
```

Going to label as a `good_first_issue` for a community member to pick up.

**Comment by dbeatty10** [comment]
Supposing the user has [dbt-duckdb](https://pypi.org/project/dbt-duckdb/) installed, the [reprex](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) ("reproducible example") is as simple as:

`dbt_project.yml`
```yaml
name: "my_dbt_project"
version: "1.0.0"
config-version: 2
profile: "sandcastle-duckdb"
```

`seeds/my_seed.csv`
```csv
id,fruit
1,orange
```

`profiles.yml`
```yaml
sandcastle-duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      schema: dev
      path: 'triage.duckdb'
      threads: 1
```
