### ISSUE TITLE
[CT-2388] [Bug] Sort metrics alphabetically while rendering metrics in the DBT documentation site

### ISSUE THREAD

**Issue by rajesh-konda** [dbt-labs/dbt-docs#410]
### Describe the feature
At present, when we look at the DBT documentation site, the metrics are not sorted in a particular order. It would be great if we have the ability to add some config at the project level or somewhere else, to specify the sorting order. Doing so would improve the site navigation for users.

### Describe alternatives you've considered
NA

### Additional context
NA
### Who will this benefit?
End users of the documentation site.

### Are you interested in contributing this feature?
Sorry, I can't help

**Comment by dbeatty10** [comment]
Thanks for opening @rajesh-konda !

Could you share a screenshot and/or a simple example showing metrics listed non-alphabetically?

It appeared to sort by the `label` of the metric (rather than the `name`) when I tried out the brief example below:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/44704949/230986773-decd6f81-ad93-48bc-b901-98239f4e6c14.png">

```yaml
version: 2

metrics:
  - name: a_rolling_new_customers
    label: Y New Customers
    model: ref('my_model')
    calculation_method: count_distinct
    timestamp: signup_date
    expression: user_id 

  - name: b_rolling_new_customers
    label: X New Customers
    model: ref('my_model')
    calculation_method: count_distinct
    timestamp: signup_date
    expression: user_id
```

**Comment by dbeatty10** [comment]
It seems like the root cause is that the list of metrics is sorted by label (everywhere), but it displays the `label` in the project listing of all metrics, but `name` in the model references.

I'd expect this to affect exposures also (any maybe some other resource types).

I'm going to label this as `good_first_issue`. See below for an implementation idea.

### Implementation idea

The easiest way to resolve this might be to display the label in the references.

Underneath here:
https://github.com/dbt-labs/dbt-docs/blob/2bdc46cc474db7ac957b4627db3eb67f34d7e70c/src/app/components/references/index.js#L23-L29

Add this new function:
```js
        scope.getNodeLabel = function(node) {
            var type = node.resource_type;
            if (type == 'exposure' || type == 'metric') {
                return node.label;
            } else {
                return node.name;
            }
        }
```

Then replace this:
https://github.com/dbt-labs/dbt-docs/blob/2bdc46cc474db7ac957b4627db3eb67f34d7e70c/src/app/components/references/index.html#L18

With this instead:
```html
        <a ng-href="{{ getNodeUrl(node) }}">{{ getNodeLabel(node) }}</a>
```

### Sample project

The following `models/_properties.yml` gives both a 

```yaml
version: 2

metrics:
  - name: a_rolling_new_customers
    label: Y New Customers
    model: ref('my_model')
    calculation_method: count_distinct
    timestamp: signup_date
    expression: user_id 

  - name: b_rolling_new_customers
    label: X New Customers
    model: ref('my_model')
    calculation_method: count_distinct
    timestamp: signup_date
    expression: user_id

exposures:

  - name: weekly_jaffle_metrics
    label: Jaffles by the Week
    type: dashboard
    maturity: high
    url: https://bi.tool/dashboards/1
    description: >
      Did someone say "exponential growth"?
    depends_on:
      - ref('my_model')
    owner:
      name: Callum McData
      email: data@jaffleshop.com
```
