### ISSUE TITLE
"Owner" field in docs site not getting populated as expected

### ISSUE THREAD

**Issue by sophiad96** [dbt-labs/dbt-docs#423]
### Describe the bug
When the `owner` config is added to a .yml file in one's dbt project, it creates an entirely new "owner" field in the docs site, rather than populating the one that already exists.

### Steps To Reproduce
Make sure you're on v1.4 or 1.5. 

1. Add the `owner` config (under the `meta` config) to either a source or model in a .yml file (examples [here](https://docs.getdbt.com/reference/resource-configs/meta)).

2.  Run `dbt docs generate`

3. Open the docs site and navigate to the source/model. You'll notice that a new "owner" field appears at the top of the "Details" section, but the existing owner field under that (see screenshot) does not get populated.

### Expected behavior
I would expect the existing "owner" field to get populated instead of an entirely new "owner" field being added.

### Screenshots and log output
<img width="480" alt="Screenshot 2023-05-18 at 11 37 29 AM" src="https://github.com/dbt-labs/dbt-docs/assets/68790165/192c141e-1727-4fb2-bf6e-a1e132825cf7">

Further context [here](https://dbt-labs.slack.com/archives/C02SRNY2EQ4/p1684432363383979), if needed.

**Comment by dbeatty10** [comment]
Thank you for opening this issue @sophiad96 and providing a nice write-up and visual aid!

This is actually behaving as expected. The difference you are seeing is between the [`meta` config](https://docs.getdbt.com/reference/resource-configs/meta#definition) which acts as an "anything" drawer and the formal model `owner` that is inherited from the model's [`group`](https://docs.getdbt.com/docs/build/groups#declaring-a-group) (new in dbt v1.5).

Example...

`models/_models.yml`
```yaml
groups:
  - name: my_group
    owner:
      name: my group owner
      email: eat@jaffle.shop

models:
  - name: my_model
    config:
      meta:
        owner:
          my meta owner
        something:
          else entirely
    group: my_group
    access: public
```

When you run `dbt docs generate` and `dbt docs serve`, you can see how these are displayed:

<img width="396" alt="image" src="https://github.com/dbt-labs/dbt-docs/assets/44704949/a5ccd7eb-a1fb-4161-b8c7-e81fea069714">

The solution in your case here would be to define the owner via the model's [`group`](https://docs.getdbt.com/docs/build/groups#declaring-a-group) instead of via the `meta` config.

Since this is behaving as expected, I'm going to close this.
