### ISSUE TITLE
[CT-2616] Docs site doesn't work if accepted_values tests has a `.nan` value

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-docs#426]
### Describe the bug
The docs site fails to load if there's a "bad" value in an `accepted_values` tests values array.

<img width="1792" alt="image" src="https://github.com/dbt-labs/dbt-docs/assets/8496748/b810bcaa-4819-4c5b-a655-4afb32f4980f">

### Steps To Reproduce

```yaml
# dbt_project.yml
name: my_dbt_project
profile: snowflake
config-version: 2
version: 1.0

models:
  my_dbt_project:
    +materialized: table

# models/schema.yml
version: 2

models:
  - name: foo
    columns:
      - name: id
        tests:
          - accepted_values:
              values:
                - 1
                - .nan
```

```sql
-- models/foo.sql
select 1 id
```

Run this:

```sh
dbt docs generate && dbt docs serve
```

### Expected behavior
Docs site should load as normal :)

### Screenshots and log output

There's a bunch of bad in the browser console but probably best for you to rerun and take a look yourself than pasting it here:

![image](https://github.com/dbt-labs/dbt-docs/assets/8496748/aa1bb80f-2b64-4f65-ae65-1d0701265f9b)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.5.1
  - latest:    1.5.1 - Up to date!

Plugins:
  - bigquery:  1.5.1 - Up to date!
  - snowflake: 1.5.1 - Up to date!
```

### Additional context
It's probably some js parsing issue - haven't looked too deeply yet.
