### ISSUE TITLE
[CT-3523] [regression] missing details for exposures in dbt docs page 

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-docs#485]
### Describe the bug
We seem to have removed owner, maturity and other fields, for Exposures in the docs, under the Details section, in version `1.6` and above.

### Steps To Reproduce
- create an exposure in a dbt project
```
exposures:

  - name: weekly_jaffle_metrics
    label: Jaffles by the Week
    type: dashboard
    maturity: high
    url: https://bi.tool/dashboards/1
    description: >
      Did someone say "exponential growth"?

    depends_on:
      - ref('my_model')

    owner:
      name: Callum McData
      email: data@jaffleshop.com
```
- generate docs dbt docs generate && dbt docs serve
- open the generated docs site and navigate to the page for the exposure

### Expected behavior
![Screenshot 2024-01-04 at 10 14 41 AM](https://github.com/dbt-labs/dbt-docs/assets/53586774/1d0c0158-8676-43c1-a990-14bbece41158)
In 1.6 and 1.7, we only see the `tags` field.

![Screenshot 2024-01-04 at 10 20 26 AM](https://github.com/dbt-labs/dbt-docs/assets/53586774/6a572b18-47af-45a8-87ec-f10c05efa206)
In 1.5, we have the full details displayed.
