### ISSUE TITLE
Presence of `saved_queries` breaks lineage viz

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-docs#486]
### Describe the bug

The lineage visualization fails to render when including `saved_queries` within `models/_properties.yml`.

### Steps To Reproduce

```yaml
semantic_models:
  - name: my_semantic_model
    model: ref('metricflow_time_spine')
    # model: ref('my_model')

metrics:
  - name: my_metric
    label: my_metric
    type: derived
    type_params:
      expr: revenue - cost

saved_queries:
  - name: p0_booking
    description: Booking-related metrics that are of the highest priority.
    query_params:
      metrics:
        - my_metric
```

```shell
dbt docs generate
dbt docs serve
```

### Expected behavior
I expected to see the entire lineage instead of a blank lineage:

<img width="500" alt="image" src="https://github.com/dbt-labs/dbt-docs/assets/44704949/1e17413d-c624-4558-9283-0509a8134856">

### Screenshots and log output

<img width="1365" alt="image" src="https://github.com/dbt-labs/dbt-docs/assets/44704949/32388e75-63cf-454f-95aa-bba3035083f7">

<img width="1351" alt="image" src="https://github.com/dbt-labs/dbt-docs/assets/44704949/0954ab2e-7526-4b50-b914-7ea4f4ac95f4">

**The output of `dbt --version`:**
```
Core:
  - installed: 1.7.4
  - latest:    1.7.4 - Up to date!

Plugins:
  - databricks: 1.7.3 - Up to date!
  - bigquery:   1.7.2 - Up to date!
  - snowflake:  1.7.1 - Up to date!
  - redshift:   1.7.1 - Up to date!
  - postgres:   1.7.4 - Up to date!
  - duckdb:     1.7.0 - Up to date!
  - spark:      1.7.1 - Up to date!
```
