### ISSUE TITLE
[Feature] Include filtered dimensions on metrics within the lineage graph

### ISSUE THREAD

**Issue by mattiasthalen** [dbt-labs/dbt-docs#518]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When defining a metric by filtering on dimensions from another semantic model, only the primary semantic model is connected in the DAG.

### Expected Behavior

All semantic models used in the metric definition are connected as upstream nodes

### Steps To Reproduce

1. Define metric
2. Filter on condition from another semantic model
3. Generate docs
4. Serve docs

### Environment

```markdown
- OS: mcr.microsoft.com/devcontainers/python:3.12-bullseye
- Python: 3.12.3
- dbt: 1.8.3
```

### Additional Context

In this case `Public Health Centers` is filtering on values from `dimension_units` via `fact_contacts > link_contacts_units`.
![image](https://github.com/dbt-labs/dbt-core/assets/2592140/60c18a0b-6c07-4d2d-b4e2-dbab51901da7)

**Comment by dbeatty10** [comment]
Thanks for reaching out @mattiasthalen !

Could you share example YAML code for these two steps to reproduce?

1. Define metric
2. Filter on condition from another semantic model

**Comment by mattiasthalen** [comment]
@dbeatty10, absolutely!

```yaml
version: 2

semantic_models:
  - name: dimension_health_centers
    label: "Health Centers"
    description: "A semantic model for health centers"
    model: ref('dimension__units')

    entities:
      - name: health_center_snapshot_hk
        expr: unit_snapshot_hk
        type: primary

    dimensions:
      - name: health_center_management
        expr: unit__management
        label: "Health Center Management"
        type: categorical

  - name: fact_contacts
    label: "Contacts"
    description: "A semantic model for contacts"
    model: ref('fact__contacts')
    defaults:
      agg_time_dimension: measurement_year_month

    entities:
      - name: fact_record_snapshot_hk
        type: primary

      - name: health_center_snapshot_hk
        type: foreign

    dimensions:        
      - name: measurement_year_month
        label: "Measurement Year Month"
        expr: (measurement_year_month||'-01')::date
        type: time
        type_params:
          time_granularity: month

    measures:  
      - name: health_centers
        expr: health_center_snapshot_hk
        description: Number of health centers
        agg: count_distinct

metrics:
  - name: health_centers
    label: Health Centers
    description: Number of health centers
    type: simple
    type_params:
      measure:
        name: health_centers
        fill_nulls_with: 0
        join_to_timespine: true

  - name: health_centers_public
    label: Public Health Centers
    description: Number of public health centers
    type: derived
    type_params:
      expr: health_centers
      metrics:
        - name: health_centers
          filter: |
            coalesce({{ Dimension('health_center_snapshot_hk__health_center_management') }}, 'private') != 'private'
```
